title: The Brown Bean
author: Naaman Hudson
email: support@forestry.io
description: >-
  ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks feature.
  This theme provides a set of page-level components and a pre-configured Forestry Blocks UI
  that will empower content editors to construct their own webpages.
url: "" # your site's origin, e.g. https://forestry.io
cloudinary_url: https://res.cloudinary.com/njh101010/image/upload
logo: /v1646598990/brownbean/web/logo.jpg
# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
plugins:
  - jekyll-feed
  - jekyll-menus
