---
label: products
hide_body: true
fields:
- type: text
  name: layout
  label: layout
  default: product
  hidden: true
- type: file
  name: image
  label: Image
- type: text
  name: title
  label: Title
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - cakes
    - breads
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
- type: textarea
  name: description
  label: Description
- type: number
  name: weight
  label: Weight
  description: Grams
- type: list
  name: ingredients
  label: Ingredients
- type: list
  name: allergens
  label: Allergens
- type: image_gallery
  name: gallery
  label: Gallery
