---
label: products
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
- type: number
  name: weight
  label: weight
- type: text
  name: category
  label: category
- type: textarea
  name: description
  label: description
- type: list
  name: ingredients
  label: ingredients
- type: image_gallery
  name: gallery
  label: gallery
- type: list
  name: allergens
  label: allergens
