---
label: Product Listings Page
hide_body: true
fields:
- type: text
  name: layout
  label: layout
  default: product-listing
  hidden: true
- type: text
  name: title
  label: Title
- type: text
  name: sub-title
  label: Sub-Title
- type: file
  name: hero-image
  label: Page Image
- type: text
  name: permalink
  label: Permalink
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - cakes
    - breads
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
