---
label: product
hide_body: false
fields:
- type: text
  hidden: true
  label: block
  name: block
  default: products
- name: category
  type: select
  default: []
  config:
    required: false
    options:
    - cakes
    - breads
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Category
